apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  METALLB_RANGE: 192.168.1.192/26
  FORWARDED_IP: 192.168.1.240
  AIRFLOW_POSTGRES_DATABASE_NAME: airflow
  AIRFLOW_POSTGRES_DATABASE_USER: airflow
  REPO_INTERVAL: 30m0s
