apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
# - cert-manager
# - ddclient
- kube-vip
# - kured
# - metallb
# - nginx
# - node-feature-discovery
# - oauth2-proxy
- reloader
# - system-upgrade
- cloudflare-tunnel
- vpn-gateway